data = [{'Unnamed: 0': 0,
  'Star_name': 'Sun',
  'Distance': '0.000015813',
  'Mass': 1.0,
  'Radius': '1'},
 {'Unnamed: 0': 1,
  'Star_name': 'Sirius',
  'Distance': '8.6',
  'Mass': 2.1,
  'Radius': '1.71'},
 {'Unnamed: 0': 2,
  'Star_name': 'Canopus',
  'Distance': '310',
  'Mass': 15.0,
  'Radius': '71'},
 {'Unnamed: 0': 3,
  'Star_name': 'Alpha Centauri',
  'Distance': '4.4',
  'Mass': 1.1,
  'Radius': '1.2'},
 {'Unnamed: 0': 4,
  'Star_name': 'Arcturus',
  'Distance': '37',
  'Mass': 1.1,
  'Radius': '26'}]

print(data)